import { notFound } from "next/navigation";
import { asc, eq } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { draftRevisions, drafts, opportunities } from "@/lib/db/schema";
import { PageHeader } from "@/components/ui";
import { DraftEditor } from "./editor";

export const dynamic = "force-dynamic";

export default async function DraftPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const database = await db();
  const [row] = await database
    .select({ draft: drafts, opportunityTitle: opportunities.title, opportunityId: opportunities.id })
    .from(drafts)
    .innerJoin(opportunities, eq(drafts.opportunityId, opportunities.id))
    .where(eq(drafts.id, id));
  if (!row) notFound();
  const revisions = await database
    .select()
    .from(draftRevisions)
    .where(eq(draftRevisions.draftId, id))
    .orderBy(asc(draftRevisions.createdAt));

  return (
    <>
      <PageHeader
        section="Drafts / Editor"
        title={row.opportunityTitle}
        meta={`${row.draft.draftType.replace(/_/g, " ")} · generated by ${row.draft.provider} provider${
          row.draft.provider === "mock"
            ? " (deterministic skeleton: bracketed slots are for Stuart's words, never invented facts)"
            : ""
        }`}
      />
      <DraftEditor
        draftId={id}
        opportunityId={row.opportunityId}
        initialContent={row.draft.content}
        initialStatus={row.draft.status}
        initialLint={row.draft.voiceLintJson ?? { errors: [], warnings: [] }}
        initialPermissionWarnings={row.draft.permissionWarningsJson ?? []}
        revisions={revisions.map((r) => ({
          id: r.id,
          author: r.author,
          note: r.revisionNote ?? "",
          at: r.createdAt?.toISOString() ?? "",
        }))}
      />
    </>
  );
}
